config/routes.rb
Rails.application.routes.draw do
  # user management
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # root path 
  root "home#index"

  # guest login 
  post '/users/guest_sign_in', to: 'guestuser#guest_sign_in'

  # top page that after login
  resources :lover, only: %i(index) do 
    collection do
      get :all
      get :search
    end
  end

  # users route 
  resources :users do 
    resources :rooms, except: %i(show create) do
      resources :messages, only: %i(create)
    end
  end

  # follows route 
  resource :follows

  # messages route 
  resource :messages, only: %i(show)

  # rooms route 
  resources :rooms, only: %i(show create)

  # categories route
  resources :categories

  # communities route
  resources :communities, only: %i(index show create)
  namespace :communities do
    resources :users, only: %i(show)
  end

  # joins route
  resources :users do 
    resources :communities, except: %i(index) do
      resource :joins, only: %i(create destroy)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # validation 
  validates :name,
            presence: true,
            length: { maximum: 30 }
            
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :age,
            presence: true
  validates :sex,
            presence: true
  
  # relation 
  has_one :profile_image, dependent: :destroy
  accepts_nested_attributes_for :profile_image
  has_many :entries
  has_many :rooms, through: :entries
  has_many :messages
  has_many :joins
  has_many :communities, through: :joins
end

app/controllers/communities/users_controller.rb
class Communities::UsersController < ApplicationController
  def show 
    @user = User.find(params[:id])
    @joined_ids = Join.where(user_id: @user.id).pluck(:community_id)
    @joined_communities = Community.where(id: @joined_ids)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # # GET /resource/sign_up
  def new
    @user = User.new 
    @profile_image = @user.build_profile_image
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :content, :blood_type, :body_shape, :height, :residence, :birth_place, :holiday, :work, profile_image_attributes: [:profile_image]])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    lover_index_path
  end

  def after_update_path_for(resource)
    lover_index_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = current_user
    @user = User.find(params[:id])
    @isFollowing = Follow.where(followed_id: @user.id).where(follower_id: @current_user.id)
    @isFollowed = Follow.where(followed_id: @current_user.id).where(follower_id: @user.id)
    @followed_ids = Follow.where(follower_id: @current_user.id).pluck(:followed_id)
    @joined_community_ids = Join.where(user_id: @user.id).pluck(:community_id)
    @joined_communities = Community.where(id: @joined_community_ids)
  end
end

app/helpers/communities/users_helper.rb
module Communities::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def show_age_user(obj)
      case obj
      when 1
        '18歳'
      when 2
        '19歳'
      when 3
        '20歳'
      when 4
        '21歳'
      when 5
        '22歳'
      when 6
        '23歳'
      when 7
        '24歳'
      when 8
        '25歳'
      when 9
        '26歳'
      when 10
        '27歳'
      when 11
        '28歳'
      when 12
        '29歳'
      when 13
        '30歳'
      when 14
        '31歳'
      when 15
        '32歳'
      when 16
        '33歳'
      when 17
        '34歳'
      when 18
        '35歳'
      when 19
        '36歳'
      when 20
        '37歳'
      when 21
        '38歳'
      when 22
        '39歳'
      when 23
        '40歳'
      when 24
        '41歳'
      when 25
        '42歳'
      when 26
        '43歳'
      when 27
        '44歳'
      when 28
        '45歳'
      when 29
        '46歳'
      when 30
        '47歳'
      when 31
        '48歳'
      when 32
        '49歳'
      when 33
        '50歳'
      when 34
        '51歳'
      when 35
        '52歳'
      when 36
        '53歳'
      when 37
        '54歳'
      when 38
        '55歳'
      when 39
        '56歳'
      when 40
        '57歳'
      when 41
        '58歳'
      when 42
        '59歳'
      when 43
        '60歳'
      end
    end
  
    def show_sex_user(obj)
      case obj
      when 1
        '男性'
      when 2
        '女性'
      end
    end
  
    def show_blood_type_user(obj)
      case obj
      when 1
        'A型'
      when 2
        'B型'
      when 3
        'O型'
      when 4
        'AB型'
      end
    end
  
    def show_body_shape_user(obj)
      case obj
      when 1
        'スリム'
      when 2
        'やや細め'
      when 3
        '普通'
      when 4
        'グラマー'
      when 5
        '筋肉質'
      when 6
        'ややぽっちゃり'
      when 7
        'ぽっちゃり'
      end
    end
  
    def show_height_user(obj)
      case obj
      when 1
        '133cm'
      when 2 
        '134cm'
      when 3
        '135cm'
      when 4
        '136cm'
      when 5
        '137cm'
      when 6
        '138cm'
      when 7
        '139cm'
      when 8
        '140cm'
      when 9
        '141cm'
      when 10
        '142cm'
      when 11
        '143cm'
      when 12
        '144cm'
      when 13
        '145cm'
      when 14
        '146cm'
      when 15
        '147cm'
      when 16
        '148cm'
      when 17
        '149cm'
      when 18
        '150cm'
      when 19
        '151cm'
      when 20
        '152cm'
      when 21
        '153cm'
      when 22
        '154cm'
      when 23
        '155cm'
      when 24
        '156cm'
      when 25
        '157cm'
      when 26
        '158cm'
      when 27
        '159cm'
      when 28
        '160cm'
      when 29
        '161cm'
      when 30
        '162cm'
      when 31
        '163cm'
      when 32
        '164cm'
      when 33
        '165cm'
      when 34
        '166cm'
      when 35
        '167cm'
      when 36
        '168cm'
      when 37
        '169cm'
      when 38
        '170cm'
      when 39
        '171cm'
      when 40
        '172cm'
      when 41
        '173cm'
      when 42
        '174cm'
      when 43
        '175cm'
      when 44
        '176cm'
      when 45
        '177cm'
      when 46
        '178cm'
      when 47
        '179cm'
      when 48
        '180cm'
      when 49
        '181cm'
      when 50
        '182cm'
      when 51
        '183cm'
      when 52
        '184cm'
      when 53
        '185cm'
      when 54
        '186cm'
      when 55
        '187cm'
      when 56
        '188cm'
      when 57
        '189cm'
      when 58
        '190cm'
      when 59
        '191cm'
      when 60
        '192cm'
      when 61
        '193cm'
      when 62
        '194cm'
      when 63
        '195cm'
      when 64
        '196cm'
      when 65
        '197cm'
      when 66
        '198cm'
      when 67
        '199cm'
      when 68
        '200cm'
      end
    end
  
      def show_residence_user(obj)
        case obj
        when 1
        '北海道'
        when 2
        '青森'
        when 3
        '岩手'
        when 4
        '宮城'
        when 5
        '秋田'
        when 6
        '山形'
        when 7
        '福島'
        when 8
        '茨城'
        when 9
        '栃木'
        when 10
        '群馬'
        when 11
        '埼玉'
        when 12
        '千葉'
        when 13
        '東京'
        when 14
        '神奈川'
        when 15
        '新潟'
        when 16
        '富山'
        when 17
        '石川'
        when 18
        '福井'
        when 19
        '山梨'
        when 20
        '長野'
        when 21
        '岐阜'
        when 22
        '静岡'
        when 23
        '愛知'
        when 24
        '三重'
        when 25
        '滋賀'
        when 26
        '京都'
        when 27
        '大阪'
        when 28
        '兵庫'
        when 29
        '奈良'
        when 30
        '和歌山'
        when 31
        '鳥取'
        when 32
        '島根'
        when 33
        '岡山'
        when 34
        '広島'
        when 35
        '山口'
        when 36
        '徳島'
        when 37
        '香川'
        when 38
        '愛媛'
        when 39
        '高知'
        when 40
        '福岡'
        when 41
        '佐賀'
        when 42
        '長崎'
        when 43
        '熊本'
        when 44
        '大分'
        when 45
        '宮崎'
        when 46
        '鹿児島'
        when 47
        '沖縄'
      end
    end
  
      def show_birth_place_user(obj)
        case obj
        when 1
        '北海道'
        when 2
        '青森'
        when 3
        '岩手'
        when 4
        '宮城'
        when 5
        '秋田'
        when 6
        '山形'
        when 7
        '福島'
        when 8
        '茨城'
        when 9
        '栃木'
        when 10
        '群馬'
        when 11
        '埼玉'
        when 12
        '千葉'
        when 13
        '東京'
        when 14
        '神奈川'
        when 15
        '新潟'
        when 16
        '富山'
        when 17
        '石川'
        when 18
        '福井'
        when 19
        '山梨'
        when 20
        '長野'
        when 21
        '岐阜'
        when 22
        '静岡'
        when 23
        '愛知'
        when 24
        '三重'
        when 25
        '滋賀'
        when 26
        '京都'
        when 27
        '大阪'
        when 28
        '兵庫'
        when 29
        '奈良'
        when 30
        '和歌山'
        when 31
        '鳥取'
        when 32
        '島根'
        when 33
        '岡山'
        when 34
        '広島'
        when 35
        '山口'
        when 36
        '徳島'
        when 37
        '香川'
        when 38
        '愛媛'
        when 39
        '高知'
        when 40
        '福岡'
        when 41
        '佐賀'
        when 42
        '長崎'
        when 43
        '熊本'
        when 44
        '大分'
        when 45
        '宮崎'
        when 46
        '鹿児島'
        when 47
        '沖縄'
      end
    end
  
      def show_holiday_user(obj)
        case obj
        when 1
        '土日'
        when 2
        '平日'
        when 3
        '不定期'
        when 4
        'その他'
      end
    end
  
      def show_work_user(obj)
        case obj
        when 1
        '上場企業'
        when 2
        '金融'
        when 3
        '公務員'
        when 4
        'コンサル'
        when 5
        '経営者・役員'
        when 6
        '大手企業'
        when 7
        '大手外資'
        when 8
        '大手商社'
        when 9
        '外資金融'
        when 10
        '医師'
        when 11
        '看護師'
        when 12
        '薬剤医師'
        when 13
        '弁護士'
        when 14
        '公認会計士'
        when 15
        'パイロット'
        when 16
        '客室乗務員'
        when 17
        '広告'
        when 18
        'マスコミ'
        when 19
        '教育関連'
        when 20
        'IT関連'
        when 21
        '食品関連'
        when 22
        '旅行関係'
        when 23
        '製薬'
        when 24
        '保険'
        when 25
        '不動産'
        when 26
        '建築関連'
        when 27
        '通信'
        when 28
        '流通'
        when 29
        'WEB関連'
        when 30
        'ブライダル'
        when 31
        'クリエイター'
        when 32
        '接客業'
        when 33
        '受付'
        when 34
        '調理師・栄養士'
        when 35
        'アパレル・ショップ'
        when 36
        '美容関係'
        when 37
        'エンターテインメント'
        when 38
        'アナウンサー'
        when 39
        '芸能・モデル'
        when 40
        'イベントコンパニオン'
        when 41
        'スポーツ選手'
        when 42
        '秘書'
        when 43
        '事務員'
        when 44
        '福祉・介護'
        when 45
        '保育士'
        when 46
        '会社員'
        when 47
        '学生'
        when 48
        '自由業'
        when 49
        '税理士'
        when 50
        'エンジニア'
        when 51
        '建築士'
        when 52
        '美容師'
        when 53
        '歯科医師'
        when 54
        '歯科衛生士'
        when 55
        'その他'
      end
      end
end

app/views/users/show.html.erb
<div class="flex justify-center gap-4">
  <div class="w-1/3 mt-5 pl-3">
   <%= render 'layouts/partial/sidenav' %>
  </div>
  <div class="w-2/3">
  <!-- component -->
<!-- This is an example component -->
<div class="w-full flex items-center justify-center bg-gray-100">
    <div class="relative w-96 h-auto bg-gray-200 rounded-md mt-20 pt-24 pb-8 px-4 shadow-md hover:shadow-lg transition flex flex-col items-center">
        <div class="absolute rounded-full bg-gray-100 w-28 h-28 p-2 z-10 -top-8 shadow-lg hover:shadow-xl transition">
            <div class="rounded-full w-full h-full overflow-auto object-cover">
                <% if @user.profile_image %>
                <%= image_tag @user.profile_image.profile_image.url, class: 'h-full w-full' %>
                <% else %>
                <%= image_tag 'profile-logo.png', class: 'w-full h-full' %>
                <% end %>  
            </div>
        </div>
        <label class="font-bold text-lg">
            <%= @user.name %>さん
        </label>
        <p class="text-center mt-2 leading-relaxed">
            <% if @user.content %>
              <%= @user.content %>
            <% else %>
              まだ自己紹介文がありません
            <% end %>
        </p>
        <div class="mt-5 flex justify-center gap-3">
          <% if @isFollowing.any? %>
          <%= link_to 'いいね！を解除', follows_path(:follower_id => @current_user.id, :followed_id => @user.id), method: :delete, class: 'block p-3 rounded-full bg-red-400 text-white font-bold hover:opacity-70' %>
          <% else %>
          <%= link_to 'いいね！を送信', follows_path(:follower_id => @current_user.id, :followed_id => @user.id), method: :post, class: 'block p-3 rounded-full bg-green-400 text-white font-bold hover:opacity-70' %>
          <% end %>
          <% if @isFollowing.any? && @isFollowed.any? %>
          <% if Entry.where(user_id: @user.id).select(:room_id).any? %>
          <%= link_to 'メッセージを送る', room_path(Entry.where(user_id: @user.id).first.room_id), class: 'block mx-auto w-40 text-center p-3 rounded-full bg-blue-400 text-white font-bold hover:opacity-70' %>
          <% else %>
          <%= link_to 'メッセージを送る', rooms_path(:partner_id => @user.id), method: :post, class: 'block mx-auto w-40 text-center p-3 rounded-full bg-blue-400 text-white font-bold hover:opacity-70' %>
          <% end %>
          <% end %>
        </div>
        <table class="table-auto mt-5 w-full">
  <thead>
    <tr>
      <th>/</th>
      <th>基本プロフィール</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>年齢</th>
      <td class="text-center"><%= show_age_user(@user.age) %></td>
    </tr>
    <tr>
      <th>血液型</th>
      <td class="text-center"><%= show_blood_type_user(@user.blood_type) %></td>
    </tr>
    <tr>
      <th>出身地</th>
      <td class="text-center"><%= show_birth_place_user(@user.birth_place) %></td>
    </tr>
  </tbody>
</table>
        <table class="table-auto mt-5 w-full">
  <thead>
    <tr>
      <th>/</th>
      <th>プロフィール項目</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th style="width: 114px;">身長</th>
      <td class="text-center"><%= show_height_user(@user.height) %></td>
    </tr>
    <tr>
      <th>体型</th>
      <td class="text-center"><%= show_body_shape_user(@user.body_shape) %></td>
    </tr>
    <tr>
      <th>職業</th>
      <td class="text-center"><%= show_work_user(@user.work) %></td>
    </tr>
    <tr>
      <th>休日</th>
      <td class="text-center"><%= show_holiday_user(@user.holiday) %></td>
    </tr>
  </tbody>
</table>
  <h1 class="font-bold mt-5">参加コミュニティ</h1>
  <% if @joined_communities.any? %>
  <div class="mt-3 flex flex-wrap justify-center items-center">
  <% @joined_communities.each do |community| %>
    <div class="item w-16 h-16 object-cover">
    <% if community.community_image? %>
    <%=image_tag community.community_image.url, class: 'w-full h-full' %>
    <% else %>
    <%= image_tag 'community.png', class: 'w-full h-full' %>
    <% end %>
    </div>
  <% end %>
  </div>
  <%= link_to 'すべてを見る', communities_user_path(@user), class: 'font-bold text-blue-400 hover:underline' %>
  <% else %>
  <p>参加コミュニティーはありません</p>
  <% end %>
      </div>
    </div>
  </div>
</div>