config/routes.rb
Rails.application.routes.draw do
  # user management
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # root path 
  root "home#index"

  # guest login 
  post '/users/guest_sign_in', to: 'guestuser#guest_sign_in'

  # top page that after login
  resources :lover, only: %i(index) do 
    collection do
      get :all
      get :search
    end
  end

  # users route 
  resources :users do 
    resources :rooms, except: %i(show create) do
      resources :messages, only: %i(create)
    end
  end

  # follows route 
  resource :follows

  # messages route 
  resource :messages, only: %i(show)

  # rooms route 
  resources :rooms, only: %i(show create)

  # categories route
  resources :categories

  # communities route
  resources :communities, only: %i(index show create)
  namespace :communities do
    resources :users, only: %i(show)
  end

  # joins route
  resources :users do 
    resources :communities, except: %i(index) do
      resource :joins, only: %i(create destroy)
    end
  end
end

app/controllers/lover_controller.rb
class LoverController < ApplicationController
  before_action :authenticate_user!
  before_action :get_current_user, only: %i(index all)
  before_action :set_q, only: %i(all search)

  def index
    @joined_ids = Join.where(user_id: @user.id).pluck(:community_id)
    @joined_communities = Community.where(id: @joined_ids).limit(3)
  end

  def all
    @all_lovers = User.where.not(id: [@user.id, 2]).page(params[:page]).per(30)
    render 'lovers'
  end

  def search
    @all_lovers = @q.result.page(params[:page]).per(30)
    @queries = request.query_parameters[:q]
    logger.debug(@all_lovers)
  end



  private
  def get_current_user
    @user = current_user
  end

  def set_q
    @user = current_user
    @q = User.where.not(id: [@user.id, 2]).ransack(params[:q])
  end
end

app/helpers/lover_helper.rb
module LoverHelper
  def show_age(obj)
    case obj
    when 1
      '18歳'
    when 2
      '19歳'
    when 3
      '20歳'
    when 4
      '21歳'
    when 5
      '22歳'
    when 6
      '23歳'
    when 7
      '24歳'
    when 8
      '25歳'
    when 9
      '26歳'
    when 10
      '27歳'
    when 11
      '28歳'
    when 12
      '29歳'
    when 13
      '30歳'
    when 14
      '31歳'
    when 15
      '32歳'
    when 16
      '33歳'
    when 17
      '34歳'
    when 18
      '35歳'
    when 19
      '36歳'
    when 20
      '37歳'
    when 21
      '38歳'
    when 22
      '39歳'
    when 23
      '40歳'
    when 24
      '41歳'
    when 25
      '42歳'
    when 26
      '43歳'
    when 27
      '44歳'
    when 28
      '45歳'
    when 29
      '46歳'
    when 30
      '47歳'
    when 31
      '48歳'
    when 32
      '49歳'
    when 33
      '50歳'
    when 34
      '51歳'
    when 35
      '52歳'
    when 36
      '53歳'
    when 37
      '54歳'
    when 38
      '55歳'
    when 39
      '56歳'
    when 40
      '57歳'
    when 41
      '58歳'
    when 42
      '59歳'
    when 43
      '60歳'
    end
  end

  def show_sex(obj)
    case obj
    when 1
      '男性'
    when 2
      '女性'
    end
  end

  def show_blood_type(obj)
    case obj
    when 1
      'A型'
    when 2
      'B型'
    when 3
      'O型'
    when 4
      'AB型'
    end
  end

  def show_body_shape(obj)
    case obj
    when 1
      'スリム'
    when 2
      'やや細め'
    when 3
      '普通'
    when 4
      'グラマー'
    when 5
      '筋肉質'
    when 6
      'ややぽっちゃり'
    when 7
      'ぽっちゃり'
    end
  end

  def show_height(obj)
    case obj
    when 1
      '133cm'
    when 2 
      '134cm'
    when 3
      '135cm'
    when 4
      '136cm'
    when 5
      '137cm'
    when 6
      '138cm'
    when 7
      '139cm'
    when 8
      '140cm'
    when 9
      '141cm'
    when 10
      '142cm'
    when 11
      '143cm'
    when 12
      '144cm'
    when 13
      '145cm'
    when 14
      '146cm'
    when 15
      '147cm'
    when 16
      '148cm'
    when 17
      '149cm'
    when 18
      '150cm'
    when 19
      '151cm'
    when 20
      '152cm'
    when 21
      '153cm'
    when 22
      '154cm'
    when 23
      '155cm'
    when 24
      '156cm'
    when 25
      '157cm'
    when 26
      '158cm'
    when 27
      '159cm'
    when 28
      '160cm'
    when 29
      '161cm'
    when 30
      '162cm'
    when 31
      '163cm'
    when 32
      '164cm'
    when 33
      '165cm'
    when 34
      '166cm'
    when 35
      '167cm'
    when 36
      '168cm'
    when 37
      '169cm'
    when 38
      '170cm'
    when 39
      '171cm'
    when 40
      '172cm'
    when 41
      '173cm'
    when 42
      '174cm'
    when 43
      '175cm'
    when 44
      '176cm'
    when 45
      '177cm'
    when 46
      '178cm'
    when 47
      '179cm'
    when 48
      '180cm'
    when 49
      '181cm'
    when 50
      '182cm'
    when 51
      '183cm'
    when 52
      '184cm'
    when 53
      '185cm'
    when 54
      '186cm'
    when 55
      '187cm'
    when 56
      '188cm'
    when 57
      '189cm'
    when 58
      '190cm'
    when 59
      '191cm'
    when 60
      '192cm'
    when 61
      '193cm'
    when 62
      '194cm'
    when 63
      '195cm'
    when 64
      '196cm'
    when 65
      '197cm'
    when 66
      '198cm'
    when 67
      '199cm'
    when 68
      '200cm'
    end
  end

    def show_residence(obj)
      case obj
      when 1
      '北海道'
      when 2
      '青森'
      when 3
      '岩手'
      when 4
      '宮城'
      when 5
      '秋田'
      when 6
      '山形'
      when 7
      '福島'
      when 8
      '茨城'
      when 9
      '栃木'
      when 10
      '群馬'
      when 11
      '埼玉'
      when 12
      '千葉'
      when 13
      '東京'
      when 14
      '神奈川'
      when 15
      '新潟'
      when 16
      '富山'
      when 17
      '石川'
      when 18
      '福井'
      when 19
      '山梨'
      when 20
      '長野'
      when 21
      '岐阜'
      when 22
      '静岡'
      when 23
      '愛知'
      when 24
      '三重'
      when 25
      '滋賀'
      when 26
      '京都'
      when 27
      '大阪'
      when 28
      '兵庫'
      when 29
      '奈良'
      when 30
      '和歌山'
      when 31
      '鳥取'
      when 32
      '島根'
      when 33
      '岡山'
      when 34
      '広島'
      when 35
      '山口'
      when 36
      '徳島'
      when 37
      '香川'
      when 38
      '愛媛'
      when 39
      '高知'
      when 40
      '福岡'
      when 41
      '佐賀'
      when 42
      '長崎'
      when 43
      '熊本'
      when 44
      '大分'
      when 45
      '宮崎'
      when 46
      '鹿児島'
      when 47
      '沖縄'
    end
  end

    def show_birth_place(obj)
      case obj
      when 1
      '北海道'
      when 2
      '青森'
      when 3
      '岩手'
      when 4
      '宮城'
      when 5
      '秋田'
      when 6
      '山形'
      when 7
      '福島'
      when 8
      '茨城'
      when 9
      '栃木'
      when 10
      '群馬'
      when 11
      '埼玉'
      when 12
      '千葉'
      when 13
      '東京'
      when 14
      '神奈川'
      when 15
      '新潟'
      when 16
      '富山'
      when 17
      '石川'
      when 18
      '福井'
      when 19
      '山梨'
      when 20
      '長野'
      when 21
      '岐阜'
      when 22
      '静岡'
      when 23
      '愛知'
      when 24
      '三重'
      when 25
      '滋賀'
      when 26
      '京都'
      when 27
      '大阪'
      when 28
      '兵庫'
      when 29
      '奈良'
      when 30
      '和歌山'
      when 31
      '鳥取'
      when 32
      '島根'
      when 33
      '岡山'
      when 34
      '広島'
      when 35
      '山口'
      when 36
      '徳島'
      when 37
      '香川'
      when 38
      '愛媛'
      when 39
      '高知'
      when 40
      '福岡'
      when 41
      '佐賀'
      when 42
      '長崎'
      when 43
      '熊本'
      when 44
      '大分'
      when 45
      '宮崎'
      when 46
      '鹿児島'
      when 47
      '沖縄'
    end
  end

    def show_holiday(obj)
      case obj
      when 1
      '土日'
      when 2
      '平日'
      when 3
      '不定期'
      when 4
      'その他'
    end
  end

    def show_work(obj)
      case obj
      when 1
      '上場企業'
      when 2
      '金融'
      when 3
      '公務員'
      when 4
      'コンサル'
      when 5
      '経営者・役員'
      when 6
      '大手企業'
      when 7
      '大手外資'
      when 8
      '大手商社'
      when 9
      '外資金融'
      when 10
      '医師'
      when 11
      '看護師'
      when 12
      '薬剤医師'
      when 13
      '弁護士'
      when 14
      '公認会計士'
      when 15
      'パイロット'
      when 16
      '客室乗務員'
      when 17
      '広告'
      when 18
      'マスコミ'
      when 19
      '教育関連'
      when 20
      'IT関連'
      when 21
      '食品関連'
      when 22
      '旅行関係'
      when 23
      '製薬'
      when 24
      '保険'
      when 25
      '不動産'
      when 26
      '建築関連'
      when 27
      '通信'
      when 28
      '流通'
      when 29
      'WEB関連'
      when 30
      'ブライダル'
      when 31
      'クリエイター'
      when 32
      '接客業'
      when 33
      '受付'
      when 34
      '調理師・栄養士'
      when 35
      'アパレル・ショップ'
      when 36
      '美容関係'
      when 37
      'エンターテインメント'
      when 38
      'アナウンサー'
      when 39
      '芸能・モデル'
      when 40
      'イベントコンパニオン'
      when 41
      'スポーツ選手'
      when 42
      '秘書'
      when 43
      '事務員'
      when 44
      '福祉・介護'
      when 45
      '保育士'
      when 46
      '会社員'
      when 47
      '学生'
      when 48
      '自由業'
      when 49
      '税理士'
      when 50
      'エンジニア'
      when 51
      '建築士'
      when 52
      '美容師'
      when 53
      '歯科医師'
      when 54
      '歯科衛生士'
      when 55
      'その他'
    end
    end
end

app/views/lover/lovers.html.erb
<div class="flex justify-center gap-4">
  <div class="w-1/3 mt-5 pl-3">
      <%= render 'layouts/partial/sidenav' %>
  </div>
<div class="w-2/3">
  <h1 class="mt-12 font-bold">探す</h1>
  <div class="w-1/6 ml-auto pr-10 text-right text-blue-400 font-bold text-3xl search-form-trigger cursor-pointer"><i class="fas fa-search"></i></div>
  <section class="px-4 mx-auto mt-12 max-w-7xl sm:px-6 lg:px-8 lg:py-20">

  <!-- search form -->
  <div class="hidden bg-gray-800 p-10 rounded-xl absolute z-10 search-form">
   <div class="mb-5 ml-auto w-12 text-xl text-white text-right font-bold cursor-pointer close-button"><i class="fas fa-times"></i></div>
  <%= search_form_for @q, url: search_lover_index_path do |search| %>
    <div class="mb-6 flex justify-start gap-10">
    <%= search.select :height_eq, {'133cm':1, '134cm':2, '135cm':3, '136cm':4, '137cm':5, '138cm':6, '139cm':7, '140cm':8, '141cm':9, '142cm':10, '143cm':11, '144cm':12, '145cm':13, '146cm':14, '147cm':15, '148cm':16, '149cm':17, '150cm':18, '151cm':19, '152cm':20, '153cm':21, '154cm':22, '155cm':23, '156cm':24, '157cm':25, '158cm':26, '159cm':27, '160cm':28, '161cm':29, '162cm':30, '163cm':31, '164cm':32, '165cm':33, '166cm':34, '167cm':35, '168cm':36, '169cm':37, '170cm':38, '171cm':39, '172cm':40, '173cm':41, '174cm':42, '175cm':43, '176cm':44, '177cm':45, '178cm':46, '179cm':47, '180cm':48, '181cm':49, '182cm':50, '183cm':51, '184cm':52, '185cm':53, '186cm':54, '187cm':55, '188cm':56, '189cm':57, '190cm':58, '191cm':59, '192cm':60, '193cm':61, '194cm':62, '195cm':63, '196cm':64, '197cm':65, '198cm':66, '199cm':67, '200cm':68}, { include_blank: '身長を選択' }, class: 'border p-3' %>
    <%= search.select :age_eq, {'18歳':1, '19歳':2, '20歳':3, '21歳':4, '22歳':5, '23歳':6, '24歳':7, '25歳':8, '26歳':9, '27歳':10, '28歳':11, '29歳':12, '30歳':13, '31歳':14, '32歳':15, '33歳':16, '34歳':17, '35歳':18, '36歳':19, '37歳':20, '38歳':21, '39歳':22, '40歳':23, '41歳':24, '42歳':25, '43歳':26, '44歳':27, '45歳':28, '46歳':29, '47歳':30, '48歳':31, '49歳':32, '50歳':33, '51歳':34, '52歳':35, '53歳':36, '54歳':37, '55歳':38, '56歳':39, '57歳':40, '58歳':41, '59歳':42, '60歳':43}, { include_blank: '年齢を選択' }, class: 'border p-3' %>
    <%= search.select :sex_eq, {'男性':1, '女性':2}, { include_blank: '性別を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6 flex justify-start gap-10">
      <%= search.select :body_shape_eq, {'スリム':1, 'やや細め':2, '普通':3, 'グラマー':4, '筋肉質':5, 'ややぽっちゃり':6, 'ぽっちゃり':7}, { include_blank: '体型を選択' }, class: 'border p-3' %>
      <%= search.select :blood_type_eq, {'A型':1, 'B型':2, 'O型':3, 'AB型':4}, { include_blank: '血液型を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6 flex justify-start gap-10">
      <%= search.select :residence_eq, {'北海道':1, '青森':2, '岩手':3, '宮城':4, '秋田':5, '山形':6, '福島':7, '茨城':8, '栃木':9, '群馬':10, '埼玉':11, '千葉':12, '東京':13, '神奈川':14, '新潟':15, '富山':16, '石川':17, '福井':18, '山梨':19, '長野':20, '岐阜':21, '静岡':22, '愛知':23, '三重':24, '滋賀':25, '京都':26, '大阪':27, '兵庫':28, '奈良':29, '和歌山':30, '鳥取':31, '島根':32, '岡山':33, '広島':34, '山口':35, '徳島':36, '香川':37, '愛媛':38, '高知':39, '福岡':40, '佐賀':41, '長崎':42, '熊本':43, '大分':44, '宮崎':45, '鹿児島':46, '沖縄':47}, { include_blank: '居住地を選択' }, class: 'border p-3' %>
      <%= search.select :birth_place_eq, {'北海道':1, '青森':2, '岩手':3, '宮城':4, '秋田':5, '山形':6, '福島':7, '茨城':8, '栃木':9, '群馬':10, '埼玉':11, '千葉':12, '東京':13, '神奈川':14, '新潟':15, '富山':16, '石川':17, '福井':18, '山梨':19, '長野':20, '岐阜':21, '静岡':22, '愛知':23, '三重':24, '滋賀':25, '京都':26, '大阪':27, '兵庫':28, '奈良':29, '和歌山':30, '鳥取':31, '島根':32, '岡山':33, '広島':34, '山口':35, '徳島':36, '香川':37, '愛媛':38, '高知':39, '福岡':40, '佐賀':41, '長崎':42, '熊本':43, '大分':44, '宮崎':45, '鹿児島':46, '沖縄':47}, { include_blank: '出身地を選択' }, class: 'border p-3' %>
      <%= search.select :holiday_eq, {'土日':1, '平日':2, '不定期':3, 'その他':4}, { include_blank: '休日を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6 flex justify-start gap-10">
      <%= search.select :holiday_eq, {'土日':1, '平日':2, '不定期':3, 'その他':4}, { include_blank: '休日を選択' }, class: 'border p-3' %>
      <%= search.select :work_eq, {'上場企業':1, '金融':2, '公務員':3, 'コンサル':4, '経営者・役員':5, '大手企業':6, '大手外資':7, '大手商社':8, '外資金融':9, '医師':10, '看護師':11, '薬剤師':12, '弁護士':13, '公認会計士':14, 'パイロット':15, '客室乗務員':16, '広告':17, 'マスコミ':18, '教育関連':19, 'IT関連':20, '食品関連':21, '旅行関係':22, '製薬':23, '保険':24, '不動産':25, '建築関連':26, '通信':27, '流通':28, 'WEB関連':29, 'ブライダル':30, 'クリエイター':31, '接客業':32, '受付':33, '調理師・栄養士':34, 'アパレル・ショップ':35, '美容関係':36, 'エンターテインメント':37, 'アナウンサー':38, '芸能・モデル':39, 'イベントコンパニオン':40, 'スポーツ選手':41, '秘書':42, '事務員':43, '福祉・介護':44, '保育士':45, '会社員':46, '学生':47, '自由業':48, '税理士':49, 'エンジニア':50, '建築士':51, '美容師':52, '歯科医師':53, '歯科衛生士':54, 'その他':55}, { include_blank: '職業を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6">
    <%= search.submit '検索', class: 'bg-blue-300 hover:bg-blue-500 w-full p-4 text-sm text-white uppercase font-bold tracking-wider cursor-pointer' %>
    </div>
    <% end %>
  </div>
  <!-- /search form -->

      <ul role="list" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4">
      <% if @all_lovers.any? %>
      <% @all_lovers.each do |lover| %>
        <li class="relative m-1">
          <div class="block overflow-hidden w-full group aspect-w-10 aspect-h-7">
            <%= link_to image_tag('profile-logo.png', class: 'object-cover pointer-events-none group-hover:opacity-75', width: 300, height: 300), user_path(lover.id) %>
            <button type="button" class="absolute inset-0 left-4 top-20">
              <span><%= lover.name %></span>
              <span><%= show_age(lover.age) %></span>
            </button>
          </div>
        </li>
      <% end %>
      <% else %>
      <p>まだ誰も登録していません</p>
      <% end %>
      </ul>
    </section>

    <%= paginate @all_lovers %>
</div>
</div>

app/views/lover/search.html.erb
<div class="flex justify-center gap-4">
  <div class="w-1/3 mt-5 pl-3">
      <%= render 'layouts/partial/sidenav' %>
  </div>
<div class="w-2/3">
  <h1 class="mt-12 font-bold"><%= @all_lovers.total_count %>人見つかりました</h1>
  <ul>
    <li>年齢:<%= show_age(@queries['age_eq'].to_i) %></li>
    <li>性別:<%= show_sex(@queries['sex_eq'].to_i) %></li>
    <li>血液型:<%= show_blood_type(@queries['blood_type_eq'].to_i) %></li>
    <li>体型:<%= show_body_shape(@queries['body_shape_eq'].to_i) %></li>
    <li>身長:<%= show_height(@queries['height_eq'].to_i) %></li>
    <li>居住地:<%= show_residence(@queries['residence_eq'].to_i) %></li>
    <li>出身地:<%= show_birth_place(@queries['birth_place_eq'].to_i) %></li>
    <li>休日:<%= show_holiday(@queries['holiday_eq'].to_i) %></li>
    <li>職業:<%= show_work(@queries['work_eq'].to_i) %></li>
  </ul>
  <div class="w-1/6 ml-auto pr-10 text-right text-blue-400 font-bold text-3xl search-form-trigger cursor-pointer"><i class="fas fa-search"></i></div>
  <section class="px-4 mx-auto mt-12 max-w-7xl sm:px-6 lg:px-8 lg:py-20">

  <!-- search form -->
  <div class="hidden bg-gray-800 p-10 rounded-xl absolute z-10 search-form">
  <div class="mb-5 ml-auto w-12 text-xl text-white text-right font-bold cursor-pointer close-button"><i class="fas fa-times"></i></div>
  <%= search_form_for @q, url: search_lover_index_path do |search| %>
    <div class="mb-6 flex justify-start gap-10">
    <%= search.select :height_eq, {'133cm':1, '134cm':2, '135cm':3, '136cm':4, '137cm':5, '138cm':6, '139cm':7, '140cm':8, '141cm':9, '142cm':10, '143cm':11, '144cm':12, '145cm':13, '146cm':14, '147cm':15, '148cm':16, '149cm':17, '150cm':18, '151cm':19, '152cm':20, '153cm':21, '154cm':22, '155cm':23, '156cm':24, '157cm':25, '158cm':26, '159cm':27, '160cm':28, '161cm':29, '162cm':30, '163cm':31, '164cm':32, '165cm':33, '166cm':34, '167cm':35, '168cm':36, '169cm':37, '170cm':38, '171cm':39, '172cm':40, '173cm':41, '174cm':42, '175cm':43, '176cm':44, '177cm':45, '178cm':46, '179cm':47, '180cm':48, '181cm':49, '182cm':50, '183cm':51, '184cm':52, '185cm':53, '186cm':54, '187cm':55, '188cm':56, '189cm':57, '190cm':58, '191cm':59, '192cm':60, '193cm':61, '194cm':62, '195cm':63, '196cm':64, '197cm':65, '198cm':66, '199cm':67, '200cm':68}, { include_blank: '身長を選択' }, class: 'border p-3' %>
    <%= search.select :age_eq, {'18歳':1, '19歳':2, '20歳':3, '21歳':4, '22歳':5, '23歳':6, '24歳':7, '25歳':8, '26歳':9, '27歳':10, '28歳':11, '29歳':12, '30歳':13, '31歳':14, '32歳':15, '33歳':16, '34歳':17, '35歳':18, '36歳':19, '37歳':20, '38歳':21, '39歳':22, '40歳':23, '41歳':24, '42歳':25, '43歳':26, '44歳':27, '45歳':28, '46歳':29, '47歳':30, '48歳':31, '49歳':32, '50歳':33, '51歳':34, '52歳':35, '53歳':36, '54歳':37, '55歳':38, '56歳':39, '57歳':40, '58歳':41, '59歳':42, '60歳':43}, { include_blank: '年齢を選択' }, class: 'border p-3' %>
    <%= search.select :sex_eq, {'男性':1, '女性':2}, { include_blank: '性別を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6 flex justify-start gap-10">
      <%= search.select :body_shape_eq, {'スリム':1, 'やや細め':2, '普通':3, 'グラマー':4, '筋肉質':5, 'ややぽっちゃり':6, 'ぽっちゃり':7}, { include_blank: '体型を選択' }, class: 'border p-3' %>
      <%= search.select :blood_type_eq, {'A型':1, 'B型':2, 'O型':3, 'AB型':4}, { include_blank: '血液型を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6 flex justify-start gap-10">
      <%= search.select :residence_eq, {'北海道':1, '青森':2, '岩手':3, '宮城':4, '秋田':5, '山形':6, '福島':7, '茨城':8, '栃木':9, '群馬':10, '埼玉':11, '千葉':12, '東京':13, '神奈川':14, '新潟':15, '富山':16, '石川':17, '福井':18, '山梨':19, '長野':20, '岐阜':21, '静岡':22, '愛知':23, '三重':24, '滋賀':25, '京都':26, '大阪':27, '兵庫':28, '奈良':29, '和歌山':30, '鳥取':31, '島根':32, '岡山':33, '広島':34, '山口':35, '徳島':36, '香川':37, '愛媛':38, '高知':39, '福岡':40, '佐賀':41, '長崎':42, '熊本':43, '大分':44, '宮崎':45, '鹿児島':46, '沖縄':47}, { include_blank: '居住地を選択' }, class: 'border p-3' %>
      <%= search.select :birth_place_eq, {'北海道':1, '青森':2, '岩手':3, '宮城':4, '秋田':5, '山形':6, '福島':7, '茨城':8, '栃木':9, '群馬':10, '埼玉':11, '千葉':12, '東京':13, '神奈川':14, '新潟':15, '富山':16, '石川':17, '福井':18, '山梨':19, '長野':20, '岐阜':21, '静岡':22, '愛知':23, '三重':24, '滋賀':25, '京都':26, '大阪':27, '兵庫':28, '奈良':29, '和歌山':30, '鳥取':31, '島根':32, '岡山':33, '広島':34, '山口':35, '徳島':36, '香川':37, '愛媛':38, '高知':39, '福岡':40, '佐賀':41, '長崎':42, '熊本':43, '大分':44, '宮崎':45, '鹿児島':46, '沖縄':47}, { include_blank: '出身地を選択' }, class: 'border p-3' %>
      <%= search.select :holiday_eq, {'土日':1, '平日':2, '不定期':3, 'その他':4}, { include_blank: '休日を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6 flex justify-start gap-10">
      <%= search.select :holiday_eq, {'土日':1, '平日':2, '不定期':3, 'その他':4}, { include_blank: '休日を選択' }, class: 'border p-3' %>
      <%= search.select :work_eq, {'上場企業':1, '金融':2, '公務員':3, 'コンサル':4, '経営者・役員':5, '大手企業':6, '大手外資':7, '大手商社':8, '外資金融':9, '医師':10, '看護師':11, '薬剤師':12, '弁護士':13, '公認会計士':14, 'パイロット':15, '客室乗務員':16, '広告':17, 'マスコミ':18, '教育関連':19, 'IT関連':20, '食品関連':21, '旅行関係':22, '製薬':23, '保険':24, '不動産':25, '建築関連':26, '通信':27, '流通':28, 'WEB関連':29, 'ブライダル':30, 'クリエイター':31, '接客業':32, '受付':33, '調理師・栄養士':34, 'アパレル・ショップ':35, '美容関係':36, 'エンターテインメント':37, 'アナウンサー':38, '芸能・モデル':39, 'イベントコンパニオン':40, 'スポーツ選手':41, '秘書':42, '事務員':43, '福祉・介護':44, '保育士':45, '会社員':46, '学生':47, '自由業':48, '税理士':49, 'エンジニア':50, '建築士':51, '美容師':52, '歯科医師':53, '歯科衛生士':54, 'その他':55}, { include_blank: '職業を選択' }, class: 'border p-3' %>
    </div>
    <div class="mb-6">
    <%= search.submit '検索', class: 'bg-blue-300 hover:bg-blue-500 w-full p-4 text-sm text-white uppercase font-bold tracking-wider cursor-pointer' %>
    </div>
    <% end %>
  </div>
  <!-- /search form -->

      <ul role="list" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4">
      <% if @all_lovers.any? %>
      <% @all_lovers.each do |lover| %>
        <li class="relative m-1">
          <div class="block overflow-hidden w-full group aspect-w-10 aspect-h-7">
            <%= link_to image_tag('profile-logo.png', class: 'object-cover pointer-events-none group-hover:opacity-75', width: 300, height: 300), user_path(lover.id) %>
            <button type="button" class="absolute inset-0 left-4 top-20">
              <span><%= lover.name %></span>
              <span><%= show_age(lover.age) %></span>
            </button>
          </div>
        </li>
      <% end %>
      <% else %>
      <p>まだ誰も登録していません</p>
      <% end %>
      </ul>
    </section>

    <%= paginate @all_lovers %>
</div>
</div>