config/routes.rb
Rails.application.routes.draw do
  # user management
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # root path 
  root "home#index"

  # guest login 
  post '/users/guest_sign_in', to: 'guestuser#guest_sign_in'

  # top page that after login
  resources :lover, only: %i(index) do 
    collection do
      get :all
      get :search
    end
  end

  # users route 
  resources :users do 
    resources :rooms, except: %i(show create) do
      resources :messages, only: %i(create)
    end
  end

  # follows route 
  resource :follows

  # messages route 
  resource :messages, only: %i(show)

  # rooms route 
  resources :rooms, only: %i(show create)

  # categories route
  resources :categories

  # communities route
  resources :communities, only: %i(index show create)
  namespace :communities do
    resources :users, only: %i(show)
  end

  # joins route
  resources :users do 
    resources :communities, except: %i(index) do
      resource :joins, only: %i(create destroy)
    end
  end
end

app/views/layouts/partial/_footer.html.erb
<div class="text-center pb-3 font-bold">
  <%= link_to '利用規約', '#', class: 'text-blue-500' %>
  <%= link_to 'プライバシーポリシー', '#', class: 'text-blue-500' %>
</div>
  <small class="block text-center pb-2 font-bold">Copyright &copy; 2021 Yuichiro Shinozaki All Rights Reserved.</small>

app/views/layouts/partial/_header.html.erb
<div class="flex justify-between items-center p-5">
  <div class="text-blue-500 text-3xl"><%= link_to 'PaiLovers', root_path %></div>
  <div class="text-blue-500 text-white">
    <%= link_to '新規登録', new_user_registration_path, class: 'p-2 mr-2 bg-green-400 rounded text-white hover:bg-gray-400 hover:text-gray-800' %>
    <%= link_to 'ログインする', new_user_session_path, class: 'p-2 bg-blue-400 rounded text-white hover:bg-gray-400 hover:text-gray-800' %>
  </div>
</div>

app/views/layouts/partial/_sidenav.html.erb
<%= link_to 'PaiLovers', lover_index_path, class: 'text-blue-500 text-3xl' %>
<ul class="text-center mt-10 text-xl">
  <li><%= link_to all_lover_index_path, class: 'hover:text-blue-400 hover:underline' do %><i class="fas fa-search"></i>&nbsp;さがす<% end %></li>
  <li class="mt-4"><%= link_to messages_path, class: 'hover:text-blue-400 hover:underline' do %><i class="fas fa-comment"></i>&nbsp;メッセージ<% end %></li>
  <li class="mt-4"><%= link_to follows_path, class: 'hover:text-blue-400 hover:underline' do %><i class="fas fa-heart"></i>&nbsp;マッチング<% end %></li>
  <li class="mt-4"><%= link_to communities_path, class: 'hover:text-blue-400 hover:underline' do %><i class="fas fa-users"></i>&nbsp;コミュニティ<% end %></li>
  <li class="mt-4"><%= link_to destroy_user_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i>&nbsp;ログアウト<% end %></li>
  <% if current_user.admin? %>
    <li class="mt-4"><%= link_to new_category_path do %><i class="fas fa-user-cog"></i>&nbsp;管理者ページ<% end %></li>
  <% end %>
</ul>