config/routes.rb
Rails.application.routes.draw do
  # user management
  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  # root path 
  root "home#index"

  # guest login 
  post '/users/guest_sign_in', to: 'guestuser#guest_sign_in'

  # top page that after login
  resources :lover, only: %i(index) do 
    collection do
      get :all
      get :search
    end
  end

  # users route 
  resources :users do 
    resources :rooms, except: %i(show create) do
      resources :messages, only: %i(create)
    end
  end

  # follows route 
  resource :follows

  # messages route 
  resource :messages, only: %i(show)

  # rooms route 
  resources :rooms, only: %i(show create)

  # categories route
  resources :categories

  # communities route
  resources :communities, only: %i(index show create)
  namespace :communities do
    resources :users, only: %i(show)
  end

  # joins route
  resources :users do 
    resources :communities, except: %i(index) do
      resource :joins, only: %i(create destroy)
    end
  end
end

app/models/community.rb
class Community < ApplicationRecord
  # validation
  validates :name,
            presence: true

  # relation
  belongs_to :category
  has_many :joins
  has_many :users, through: :joins

  # for carrierwave
  mount_uploader :community_image, CommunityImageUploader  
end

app/controllers/communities/users_controller.rb
class Communities::UsersController < ApplicationController
  def show 
    @user = User.find(params[:id])
    @joined_ids = Join.where(user_id: @user.id).pluck(:community_id)
    @joined_communities = Community.where(id: @joined_ids)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :get_all, only: %i(index create)
  before_action :set_q, only: %i(index)

  def index
    @category = Category.new 
    @community = @category.communities.build
    @all_communities = @q.result
  end

  def create
    @community = Community.new(community_params)

    if @community.save 
      redirect_to communities_index_path
    else
      render 'index'
    end
  end

  def search
    
  end

  def show
    @user = current_user
    @community = Community.find(params[:id])
    @isJoin = Join.where(user_id: @user.id).where(community_id: @community.id)
    @guest_user_ids = Join.where(community_id: @community.id).pluck(:user_id)
    @guests = User.where(id: @guest_user_ids)
  end

  private 
  def get_all
    @all_communities = Community.order(created_at: 'desc').all
  end

  def community_params
    params.require(:community).permit(:category_id, :name, :community_image)
  end

  def set_q
    @q = Community.ransack(params[:q])
  end
end

app/helpers/communities/users_helper.rb
module Communities::UsersHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
  def show_age_community(obj)
    case obj
    when 1
      '18歳'
    when 2
      '19歳'
    when 3
      '20歳'
    when 4
      '21歳'
    when 5
      '22歳'
    when 6
      '23歳'
    when 7
      '24歳'
    when 8
      '25歳'
    when 9
      '26歳'
    when 10
      '27歳'
    when 11
      '28歳'
    when 12
      '29歳'
    when 13
      '30歳'
    when 14
      '31歳'
    when 15
      '32歳'
    when 16
      '33歳'
    when 17
      '34歳'
    when 18
      '35歳'
    when 19
      '36歳'
    when 20
      '37歳'
    when 21
      '38歳'
    when 22
      '39歳'
    when 23
      '40歳'
    when 24
      '41歳'
    when 25
      '42歳'
    when 26
      '43歳'
    when 27
      '44歳'
    when 28
      '45歳'
    when 29
      '46歳'
    when 30
      '47歳'
    when 31
      '48歳'
    when 32
      '49歳'
    when 33
      '50歳'
    when 34
      '51歳'
    when 35
      '52歳'
    when 36
      '53歳'
    when 37
      '54歳'
    when 38
      '55歳'
    when 39
      '56歳'
    when 40
      '57歳'
    when 41
      '58歳'
    when 42
      '59歳'
    when 43
      '60歳'
    end
  end
end

app/views/communities/index.html.erb
<div class="flex justify-center gap-4">
  <div class="w-1/3 mt-5 pl-3">
   <%= render 'layouts/partial/sidenav' %>
  </div>
  <div class="w-2/3">
    <h1 class="mt-10 text-xl font-bold">コミュニティ一覧</h1>
    <!-- create community button -->
    <div class="text-blue-400 cursor-pointer fixed right-3 top-12 create-community-form-trigger"><i class="fas fa-plus"></i>&nbsp;コミュニティ作成</div>
    <!-- /create community button -->

    <!-- search form -->
    <%= search_form_for @q, url: communities_path, class: 'mt-10' do |search| %>
    <%= search.text_field :name_cont, class: 'p-2 rounded-xl border',  placeholder: 'コミュニティー名で検索' %>
    <%= search.submit '検索', class: 'p-2 bg-blue-400 text-white rounded-full cursor-pointer' %>
    <% end %>
    <!-- /search form -->

    <!-- create community form -->
    <div class="hidden bg-gray-800 p-10 rounded-xl absolute z-10 create-community-form">
      <div class="mb-5 ml-auto w-12 text-xl text-white text-right font-bold cursor-pointer close-button"><i class="fas fa-times"></i></div>
      <%= form_with model: @community, url: communities_path, local: true do |new_community| %>
      <div class="mb-6">
      <%= new_community.text_field :name, class: 'border w-full p-3', placeholder: 'コミュニティー名' %>
      </div>
      <div class="mb-6">
      <%= new_community.select :category_id, {'ゲーム':1, 'スポーツ':2, '音楽':3, '恋愛・結婚':4, '美容・健康':5, '仕事':6, 'ペット・動物':7, 'カフェ':8, 'アート':9, 'ファッション':10, 'フード・お酒':11, '旅行':12}, { include_blank: 'カテゴリーを選択' }, class: 'w-full p-3' %>
      </div>
      <div class="mb-6">
      <%= new_community.file_field :community_image, class: 'text-white border p-2' %>
      </div>
      <div class="mb-6">
      <%= new_community.submit '作成', class: 'w-24 block p-3 ml-auto mb-5 rounded-full bg-blue-400 text-white font-bold hover:opacity-70 cursor-pointer' %>
      </div>
      <% end %>
    </div>
    <!-- /create community form -->

    <% if @all_communities.any? %>
      <div class="mt-16 flex flex-wrap justify-center items-center gap-8">
      <% @all_communities.each do |community| %>
        <div class="item w-32 h-32 object-cover">
          <figure class="h-full">
            <% if community.community_image? %>
            <%= image_tag community.community_image.url, class: 'border-4 h-full' %>
            <% else %>
            <%= image_tag 'community.png', class: 'border-4 h-full' %>
            <% end %>
            <figcaption><%= link_to community.name, community_path(community), class: 'hover:text-blue-400 underline' %></figcaption>
          </figure>
        </div>
      <% end %>
      </div>
    <% else %>
      <p>まだ何もありません</p>
    <% end %>
  </div>
</div>

app/views/communities/show.html.erb
<div class="flex justify-center gap-4">
  <div class="w-1/3 mt-5 pl-3">
   <%= render 'layouts/partial/sidenav' %>
  </div>
  <div class="w-2/3">
    <div class="mt-10">
        <% if @community.community_image? %>
        <%= image_tag @community.community_image.url, class: 'border-4 h-full w-32 h-32' %>
        <% else %>
        <%= image_tag 'community.png', class: 'border-4 w-32 h-32' %>
        <% end %>
        <span class="text-xl font-bold"><%= @community.name %></span>
    </div>
    
    <% if @isJoin.any? %>
    <%= link_to 'このコミュニティーから退会する', user_community_joins_path(@user, @community), method: :delete, class: 'mt-5 inline-block p-3 rounded-full bg-red-400 text-white font-bold hover:opacity-70 cursor-pointer' %>
    <% else %>
    <%= link_to 'このコミュニティーに参加する', user_community_joins_path(@user, @community), method: :post, class: 'mt-5 inline-block p-3 rounded-full bg-blue-400 text-white font-bold hover:opacity-70 cursor-pointer' %>
    <% end %>

    <h1 class="mt-3 text-xl">このコミュニティーの参加者(<%= @guests.size %>人)</h1>
    <ul role="list" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4">
    <% if @guests.any? %>
    <% @guests.each do |guest| %>
      <li class="relative m-1">
        <div class="block overflow-hidden w-full group aspect-w-10 aspect-h-7">
          <% if guest.id == current_user.id %>
          <%= link_to image_tag('profile-logo.png', class: 'object-cover pointer-events-none group-hover:opacity-75', width: 300, height: 300), lover_index_path %>
          <% else %>
          <%= link_to image_tag('profile-logo.png', class: 'object-cover pointer-events-none group-hover:opacity-75', width: 300, height: 300), user_path(guest.id) %>
          <% end %>
          <button type="button" class="absolute inset-0 left-4 top-20">
            <span><%= guest.name %></span>
            <span><%= show_age_community(guest.age) %></span>
          </button>
        </div>
      </li>
    <% end %>
    <% else %>
    <p class="mt-5">まだ誰も登録していません</p>
    <% end %>
    </ul>
  </div>
</div>